### ISSUE TITLE
Multiple images on the detail page

### ISSUE THREAD

**Issue by barbarah** [colonial-heritage/colonial-collections#83]
See the design https://xd.adobe.com/view/6835967b-8f38-490d-9e8d-1df0163f7bc5-3d66/screen/0077db1c-0c6e-40a7-ab95-410aaa293c29

**Comment by barbarah** [comment]
There can be multiple images. The order of the images is random. The images can be landscape or portrait. @Doppen Can you make a design for this?

**Comment by Doppen** [comment]
Yes
